### ISSUE TITLE
eZProtector 4.0.1: Not preventing players using the /? even thou enabled in the config 

### ISSUE THREAD

**Issue by c0mput3** [dvargas135/eZProtector#1]
Hi

Players are still able to use the /? command even thou it has been set within the config to prevent them from being able to.

This is effected on version eZProtector 4.0.1

**Comment by dvargas135** [comment]
Hello,

What version are you using which is not blocking the tab completion?

Thanks.

**Comment by dvargas135** [comment]
My bad, the /? Command.

**Comment by c0mput3** [comment]
Hi

if you type /? <pagenumber> the command is executed and display
the corresponding page

**Comment by dvargas135** [comment]
What version are you using?

**Comment by c0mput3** [comment]
eZProtector 4.0.1

**Comment by dvargas135** [comment]
I meant spigot version. Anyways... This is going to be fixed on the next update. Thanks for reporting!

**Comment by dvargas135** [comment]
This has been fixed on eZProtector 4.0.2.
