### ISSUE TITLE
PlayerCommandPreprocessEvent on 4.0.2

### ISSUE THREAD

**Issue by LeDadSnatcher** [dvargas135/eZProtector#10]
Hey man, you said last time that this was fixed however, I think you got this confused with the other person who said they were getting the same error when their issue was whenever someone tried doing a blocked command, mine is when someone does ANY command. I've updated and I'm still getting this error: 

http://pastebin.com/AA76y0EU

Here's my config too if you need it: http://pastebin.com/uYZWkw4H

PaperSpigot 1.8.8 (Also tried Spigot 1.8.8)
Java 8 
ProtocolLib 4.1
Vault 1.5.6

**Comment by dvargas135** [comment]
Hello,

Try adding '?' Instead of just "?".
In ur config:
- '?'

Tell me if it works!

**Comment by LeDadSnatcher** [comment]
Doesn't fix the error for me.

**Comment by dvargas135** [comment]
For who else then? Lol. Try deleting your config so the plugin makes a new one. Don't forget to make a backup of your old one if you had custom messages, settings, etc.

**Comment by LeDadSnatcher** [comment]
Seems to be fixed now, a reload didn't fix the issue but after a restart, it seems all good.
