### ISSUE TITLE
mod whitelisting?

### ISSUE THREAD

**Issue by pookshuman** [dvargas135/eZProtector#14]
Right now I am using this plugin to block all loaders. Mainly this is because I don't have the time to research every mod to check if it is "cheaty." I feel like if I allow forge so people can use a minimap, that also lets them use any other mod that is not in the EZP config list.

My understanding is that EZP allows all mods with the exception of a handful in the config list. Is there any way to reverse this function and disallow all mods unless they are whitelisted? In other words, I want to be able to block all mods that are not in the config list.

Is this possible? 
Thanks for your time

**Comment by dvargas135** [comment]
Hello,

Only the mods in the list can be blocked. If you'd like any others blocked don't hesitate to suggest them and I'll try to block them.

Thanks for using eZProtector!

**Comment by pookshuman** [comment]
OK, definitely not what i was looking for, but thank you for your time :)
