### ISSUE TITLE
have 2 bug report

### ISSUE THREAD

**Issue by SirAbdullah** [dvargas135/eZProtector#18]
when i block command from the config like /me or /tell if someone type /tell or /me will say error message but when he say /tell argument like name and messgae the command will work

2 problem is the damage indicators not blocked in 1.7.10 version i dont know if it work with other versions or not and Thank you!

**Comment by SirAbdullah** [comment]
and this my config if you need it http://pastebin.com/PJmhqLQd

**Comment by dvargas135** [comment]
Hello, please make a backup of your old config and delete it from the plugin folder so a new one is created. After that you can add what you added before to the new config. You have an old configuration.

**Comment by dvargas135** [comment]
With no further feedback given I'll just close this issue. If the problem persists please open a new issue.
