### ISSUE TITLE
Client displays crash message instead of kick message when kicked for Forge mod

### ISSUE THREAD

**Issue by MrPNutts** [dvargas135/eZProtector#19]
Love this plugin, but I'm having an issue.

Latest version 4.0.4 on hosted Spigot 1.10.2. Not many plugins but I will reproduce with just this one and it's dependencies if needed. No errors on load.

After installing, enabling Forge protection, and restarting the server (a couple of times), when I join with forge-1.10.2-12.18.1.2077 (which reports as beta on launch) I am kicked as expected, but instead of the expected message to the player (punish-command: kick %player% The Forge mod is not allowed.) the client crashes with a normal crash error "Connection Lost - Internal exception blah blah blah connection forcibly closed by the remote host.". Notice I took out &4 as part of my testing. I'll download some of the other mods to see if the behavior is global.

I don't want to make anyone think there's a problem with their client. I'll test some more with different versions of Forge. Thank you!

**Comment by MrPNutts** [comment]
Oops. I forgot to mention the logs look great. I'll get them from my laptop and paste the link here.

**Comment by dvargas135** [comment]
Hello, the kick message isn't 100% probable to appear. I still don't know the reason of this, but it's the same for the world downloader mod and the liteloader mod.

**Comment by MrPNutts** [comment]
Gotcha. Thank you for the response. Again, a very awesome mod!
