### ISSUE TITLE
1.11 compatibility

### ISSUE THREAD

**Issue by lululombard** [dvargas135/eZProtector#21]
Hello ! It seems that the plugin is not compatible with 1.11.
Could you update it ? Thanks.

**Comment by afroman84** [comment]
please @dvargas135 let us know something :) would be really appreciated

**Comment by dvargas135** [comment]
Hello, I'll update the plugin once I get home today (in about 3 hours). Thanks for notifying me about this and for using eZProtector!

**Comment by dvargas135** [comment]
Updated.
