### ISSUE TITLE
Liteloader not blocked for 1.11?

### ISSUE THREAD

**Issue by Fonzee9** [dvargas135/eZProtector#22]
Bug please fix?

**Comment by 7rory768** [comment]
Is this still an issue in the latest version?

**Comment by Fonzee9** [comment]
Yeah

**Comment by dvargas135** [comment]
Some mods can't be fully blocked. Mod authors can decide to remove or change the way how eZP blocks mods and because of that, they're not blocked.

**Comment by DoNotSpamPls** [comment]
The latest version of eZProtector should block LiteLoader properly.
