### ISSUE TITLE
Command Whitelist

### ISSUE THREAD

**Issue by AcesGamingUK** [dvargas135/eZProtector#23]
option to whitelist certain commands or a permission 

let's say I've blocked all colon commands.
but I need players to issue this:command

a section where I could add this to be exempt from the block list would be great
or a perm node
ezprotector.bypass.command.this.command

**Comment by TransportLayer** [comment]
I would like to see this feature implemented as well. A way to allow specific subcommands but block the top level command (and other subcommands) would be useful to me.

**Comment by CloudeLecaw** [comment]
Pls dont make new sugestions anymore :(
Why? The development was closed by the dev
So its not usefull anymore to creat suggestions or ask for bug fixes :(

**Comment by DoNotSpamPls** [comment]
That feature was added in the latest version of eZProtector 😃
