### ISSUE TITLE
Plugin = 0

### ISSUE THREAD

**Issue by mark27205** [dvargas135/eZProtector#28]
The plugin doesn't  works.
Players with Schematica or Worlddownloader can join.
Blocked Commands = will not broadcast

**Comment by 7rory768** [comment]
Are there any startup errors? What does work?

**Comment by dvargas135** [comment]
Schematica and other mods can't be fully blocked. Notifies have been fixed.

**Comment by DoNotSpamPls** [comment]
There shouldn't be any issues with the latest version 😛
