### ISSUE TITLE
Commands I have set to block. Are not being blocked?

### ISSUE THREAD

**Issue by Linebeck** [dvargas135/eZProtector#31]
Idk what it is but players are still able to use commands. I have a chat plugin, in older versions it blocked /chc. Now anyone can use it even tho its on the blacklist of the config. Same goes for people who are opped, I added commands to that list and it doesn't recognize it. However, it works when a regular player trys to do "/?"....

**Comment by Linebeck** [comment]
Everything worked on 1.10

**Comment by dvargas135** [comment]
This was fixed on latest version.
