### ISSUE TITLE
Addition request

### ISSUE THREAD

**Issue by Metisuneatn** [dvargas135/eZProtector#33]
I am pretty new to the plugin so I am not sure if this is possible but is there a way to disabled mods like inventory tweaks?

**Comment by Eyremba** [comment]
> I am pretty new to the plugin so I am not sure if this is possible but is there a way to disabled mods like inventory tweaks?

Just use NoCheatPlus, it disables InventoryTweaks.

**Comment by Metisuneatn** [comment]
NoCheat clashes with too many plugins D: Will try to see if I can get it to work with them again
