### ISSUE TITLE
ViaVersion compatibility issue

### ISSUE THREAD

**Issue by PlugITNow** [dvargas135/eZProtector#35]
Hello, as I just see thins bug tracker I paste the message I left on the discuss : 

there is a bug on 1.8.8 paperspigot sever with ViaVersion, all players can't connect in 1.9+ for :

DecoderExeption : java.lang.IndexOutOfBoundsExeption: readerIndex(0)
+length(1)exceeds writerIndex(0): UnpooledSliceByteBuf(ridx: 0, widx: 0,cap 0/0, unwrapped: PooledUnsafeDirectByteBuf (ridx: 5796, widx: 5802, cap: 8192)) @ io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by dvargas135** [comment]
This plugin does not interfere in any way with the Minecraft protocols, which are the ones used to allow players from different versions join your server.
