### ISSUE TITLE
handleDisconnection() called twice and no Mesagges?

### ISSUE THREAD

**Issue by Magino0088** [dvargas135/eZProtector#37]
I have but also if I now block WDL comes always only separated when a player comes in and he does not see the warning.

UUID of player Magino is 24kdl42jf9-ef17-40fb-b554-abc18hdjgf5fd
Magino[/293.885.904.61:35648] logged in with entity id 1 at ([worlds1]238.5399547307894, 72.0, 193.12202620912032)
Magino lost connection: �4The World Downloader Mod is not allowed.
Magino left the game
Kicked Prymo from the game: '�4The World Downloader Mod is not allowed.'
[WDLCompanion] Player Prymo has WDL installed.
[WDLCompanion] They are located in world world, at 238.58557646647894, 72.0, 193.12202620912032.
[WDLCompanion] They are running WDL version {"X-RTFM":"http://wiki.vg/Plugin_channels/World_downloader","X-UpdateNote":"The plugin message system will be changing shortly. Please stay tuned.","Version":"4.0.0.3","State":"Init?"}.

WARN
04.04.2017 17:36:07
17:36:07
handleDisconnection() called twice
![wdl](https://cloud.githubusercontent.com/assets/26903716/24665739/971d86d2-195e-11e7-8de6-73db309d8f41.PNG)

**Comment by GiansCode** [comment]
I will attempt to fix the warning in the coming updates, but, the handleDisconnection is a Spigot issue
