### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by pedrocarcamo** [dvargas135/eZProtector#39]
the Hidden Syntaxes thing doesn't fully work. 

It does not block /minecraft:

**Comment by dvargas135** [comment]
The /minecraft: commands are the reason that feature exists. The code should always work with any command unless @GiansCode changed anything, which I doubt.

Check if you enabled the feature in the plugin config or if there are errors in the console regarding eZProtector.

**Comment by pedrocarcamo** [comment]
is enabled and does not work, that is why I opened an issue.

**Comment by GiansCode** [comment]
Haven't changed a thing and cannot recreate this using latest version on 1.11. Maybe 1.12 changed something, I'll test this when I finish the update in the coming days (just been incredibly busy).

**Comment by dvargas135** [comment]
Just realized the plugin hasn't been updated for 1.12 therefore shouldn't even enable itself on startup. @pedrocarcamo please wait for an update before posting possible bugs with newer versions of minecraft/spigot.
