### ISSUE TITLE
Minecraft Version

### ISSUE THREAD

**Issue by LoYungSum** [dvargas135/eZProtector#43]
I cannot use this plugin with 1.8.8 spigot
If you know why, please send an email to: sumsum_2003@yahoo.com.hk
Thanks

**Comment by dvargas135** [comment]
I have added support for 1.12 by adding a missing class. I haven't tested the update yet, you can test it for me and comment here if there are any issues.

You can find my update here: https://github.com/dvargas135/eZProtector/releases/latest (with support from versions 1.7 to 1.12 and no new features)
Or Gianluca's update here: https://www.spigotmc.org/resources/ezprotector.12663/ (with support for 1.9, 1.10, 1.11 and 1.12 versions and possible new features in a future)
