### ISSUE TITLE
PaperSpigot 1.7.10 Compatibility

### ISSUE THREAD

**Issue by jCripton** [dvargas135/eZProtector#44]
eZProtector don't work on PaperSpigot 1.7.10, fix it please.
I've ProtocolLib 4.3.0 and Vault but don't work,it is red in plugin's list.
If you fix it,i'll give you money. I really need it, your plugin is useful :(

**Comment by dvargas135** [comment]
I have added support for 1.12 by adding a missing class. I haven't tested the update yet, you can test it for me and comment here if there are any issues.

You can find my update here: https://github.com/dvargas135/eZProtector/releases/latest
Or Gianluca's update here: https://www.spigotmc.org/resources/ezprotector.12663/

**Comment by jCripton** [comment]
I tried your update. The plugin works but not properly. 1) When you enter the server with a forbidden mode, it does not exit the kick's message but 'Internal Exception' message and the console kick you after 2 seconds that you've entered on the server. Another advice I give you is to add the Ocmc mod, with which you can download the worlds

**Comment by dvargas135** [comment]
You may discuss this with the plugin maintainer, I just updated it so it works for you lol.

Thanks for using the plugin
