### ISSUE TITLE
Plugin not working for me @Spigot 1.8.8

### ISSUE THREAD

**Issue by itsTyrion** [dvargas135/eZProtector#55]
I was happy to find this plugin, and decided to put it on my Server, a work-in-progress Bungeecord-Network with Cloudsystem. It didn't seem to work though, so I checked the logs. 
[04:20:49] [Server thread/INFO]: [eZProtector] Enabling eZProtector v4.1.6
[04:20:49] [Server thread/WARN]: [eZProtector] Your server version is not compatible with eZProtector.
[04:20:49] [Server thread/INFO]: [eZProtector] Disabling eZProtector v4.1.6

I tried downloading a fresh copy, and running it on a spigot 1.8.8 testserver on my pc, same result. 

How can this be? I thought it is compatible with a "Spigot server running on any 1.7, 1.8, 1.9, 1.10, or 1.11 versions."

**Comment by CloudeLecaw** [comment]
hm sometime  ithink people never read or look for other issues. This issues is solved allready
https://github.com/dvargas135/eZProtector/issues/54

**Comment by DoNotSpamPls** [comment]
This issue has been completely removed in the newest versions of eZProtector, you should update.
