### ISSUE TITLE
Forge 1.13.2 Is Out (Link in Desc.)

### ISSUE THREAD

**Issue by pinkpig3777** [dvargas135/eZProtector#72]
I can't seem to find my old issue report so I've created a new one. 

Forge 1.13.2 has been released, so could you please add a block for it? Thank you! :) 

Link: https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.13.2.html

**Comment by DoNotSpamPls** [comment]
First, you are on the wrong repository! You should report to DoNotSpamPls/eZProtector.

Thanks for the heads-up anyway, I'll be sure to add this when I can.

**Comment by pinkpig3777** [comment]
Ah whoops. Sorry. I know you've seen it now, so I'm not sure if I should post it at correct location. I will just in case.  

https://github.com/DoNotSpamPls/eZProtector/issues/37

Thank you!
