### ISSUE TITLE
1.7 Support Please?

### ISSUE THREAD

**Issue by spannerman79** [dvargas135/eZProtector#9]
As per your statement from  https://www.spigotmc.org/resources/ezprotector.12663/update?update=111475 I am respectfully requesting a 1.7 compatible version of your plugin.

**Comment by dvargas135** [comment]
Hey,

You can download the latest eZProtector version for 1.7.x here:
https://mega.nz/#!JRA2BT6C!MFN6lyzjb98tN-Ps6Gcq4wpaF-WBILGEqaoUGthBfB0

Greetings,
Dan

**Comment by dvargas135** [comment]
Hey,

You can download the latest eZProtector version for 1.7.x here:
https://mega.nz/#!JRA2BT6C!MFN6lyzjb98tN-Ps6Gcq4wpaF-WBILGEqaoUGthBfB0

Greetings,
Dan

**Comment by DoNotSpamPls** [comment]
Also, the latest eZProtector version supports all 1.7-1.12 version 😛
